config/routes.rb
Rails.application.routes.draw do
 devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'books#index'
  get 'books/search' => 'books#search'
  resources :books do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show]
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy
  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :book               #tweetsテーブルとのアソシエーション
  belongs_to :user                #usersテーブルとのアソシエーション
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :book, counter_cache: :likes_count
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books
  has_many :comments
  has_many :likes

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = User.create(name: auth.extra.raw_info.name,
                         provider: auth.provider,
                         uid: auth.uid,
                         email: auth.info.email,
                         password: Devise.friendly_token[0, 20]
                         )
    end
    user
  end


  def self.create_unique_string
    SecureRandom.uuid
  end

  private
  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_user




  private

  def after_sign_out_path_for(resource)
    '/users/sign_in' # サインアウト後のリダイレクト先URL
  end

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
require 'json'
require 'net/https'

class BooksController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index
    @books = Book.includes(:user).order("created_at DESC").page(params[:page]).per(10)
    @likes = Like.where(user_id: current_user)
  end

  def search
    if params[:keyword].present?
      app_id = '1094834126119853128'
      searchTitle = params[:keyword]

      https = Net::HTTP.new('app.rakuten.co.jp', 443)
      https.use_ssl = true
      https.ca_file = 'nil'
      https.verify_mode = OpenSSL::SSL::VERIFY_NONE
      https.verify_depth = 5

      https.start {
        response = https.get("/services/api/BooksBook/Search/20130522?format=json&applicationId=#{app_id}&title=#{searchTitle}")
        document = JSON.parse(response.body);
        @items = document["Items"] || []
      }
    end
  end

  def new
    @title = params[:title]
    @author = params[:author]
    @book_image = params[:book_image]
    @publisher = params[:publisher]
  end

  def create
        Book.create(title: book_params[:title], author: book_params[:auther], publisher: book_params[:publisher], image: book_params[:image],review: book_params[:review], rate: book_params[:rate], user_id: current_user.id)
      redirect_to controller: :books, action: :index
  end

  def destroy
      book = Book.find(params[:id])
      book.destroy if book.user_id == current_user.id
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
      book = Book.find(params[:id])
      if book.user_id == current_user.id
        book.update(book_params)
      end
  end

  def show
    @book = Book.find(params[:id])
    @comments = @book.comments.includes(:user)
  end



  private
    def book_params
      params.permit(:title, :author, :publisher, :image, :review, :rate)
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], book_id: comment_params[:book_id], user_id: current_user.id)
    redirect_to "/books/#{@comment.book.id}"
  end

  private
  def comment_params
    params.permit(:text, :book_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, book_id: params[:book_id])
    @book = Book.includes(:user).find(params[:book_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, book_id: params[:book_id])
    like.destroy
    @book = Book.includes(:user).find(params[:book_id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to :root
    end
    # callback_from :facebook
  end

  # def twitter
  #   callback_from :twitter
  # end

  # private
  # def callback_from(provider)
  #   provider = provider.to_s

  #   @user = User.find_for_oauth(request.env['omniauth.auth'])

  #   if @user.persisted?
  #     flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
  #     sign_in_and_redirect @user, event: :authentication
  #   else
  #     session["devise.#{provider}_data"] = request.env['omniauth.auth']
  #     redirect_to new_user_registration_url
  #   end
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # coding: utf-8

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path, :notice => 'サインインしました'
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_path, :notice => ' サインアウトしました'
  end

  def oauth_failure
    redirect_to root_path, :notice => ' サインイン処理が中断されました'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @books = user.books.order("created_at DESC")
    userlikes = Like.where(user_id: user.id)

    userlikebook_id = userlikes.map {|userlike| userlike.book_id }
    @bookmarks = userlikebook_id.map {|ele| Book.find(ele)}

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/create.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/books/destroy.html.erb
<div class="col-md-4 col-md-offset-4">
    <div>
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
</div>

app/views/books/edit.html.erb
<div class="new_contents">
<div>
  <%= form_tag("/books/#{@book.id}", method: :patch) do %>
    <h2 class=category_title>
      Edit
    </h2>
    <ul style = "list-style:none" class = "col-md-4 col-md-offset-4">
        <li><input class="new_post" placeholder="本のタイトル" type="text" name="title" value="<%= @book.title %>"></li>
        <li><input class="new_post" placeholder="著者名" type="text" name="author" value="<%= @book.author %>"></li>
        <li><input class="new_post" placeholder="出版社" type="text" name="publisher" value = "<%= @book.publisher %>"></li>
        <li><input class="new_post" placeholder="Image Url" type="text" name="image" value = "<%= @book.image %>"></li>
        <li class="evaluation">
              <input id="star1" type="radio" name="star" value="5" />
              <label for="star1"><span class="text"></span>★</label>
              <input id="star2" type="radio" name="star" value="4" />
              <label for="star2"><span class="text"></span>★</label>
              <input id="star3" type="radio" name="star" value="3" />
              <label for="star3"><span class="text"></span>★</label>
              <input id="star4" type="radio" name="star" value="2" />
              <label for="star4"><span class="text"></span>★</label>
              <input id="star5" type="radio" name="star" value="1" />
              <label for="star5"><span class="text"></span>★</label>
        </li>
        <li><textarea class = "review" cols="70" name="review" placeholder="要約・感想など" rows="10"><%= @book.review %></textarea></li>
        <li><Button class = "button_type submit_button" type="submit">SEND</Button></li>
    </ul>
  <% end %>
  </div>
</div>

app/views/books/index.html.erb
<div class="contents">
  <h2 class= category_title> Timeline </h2>
  <div class="row row-eq-height">
    <% @books.each do |book| %>
      <div class="col-md-4 col-sm-5 col-sm-offset-1 col-xs-10 col-xs-offset-1 book_container">
        <div class = "row" >
          <div class="col-md-4 book_image"><img src=<%= book.image %>></div>
          <div class="col-md-6 text">
            <a href="/books/<%=book.id%>}">
              <h4><%= book.title %></h4>
            </a>
            <p>著者名：<%= book.author %><p>
            <p>出版社：<%= book.publisher %><p>
            <i class="glyphicon glyphicon-user"></i><a href="/users/<%= book.user_id %>"><%= book.user.name %></a>
            <div class="wrap">
              <span class="rate rate<%=book.rate%>"></span>
            </div>
            <p class=review_contents><%= book.review %></p>
            <a class = comment href="/books/<%=book.id%>"> Comment >> </a>
            <div class="book_amazon"><%= link_to"購入を検討>>","http://amazon.jp/gp/search?ie=UTF8&keywords=#{book.title}#{book.author}", target: "_blank" %>
            </div>
          </div>
          <div id= "like-button<%= book.id %>", class="col-md-1 likes">
              <% if user_signed_in? %>
                  <%= render partial: "likes/like", locals: { book: book, like: book.likes.where(user_id: current_user.id).first } %>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate(@books) %>
</div>

app/views/books/new.html.erb
<div class="new_contents">
<div>
  <%= form_tag('/books', method: :post) do %>
    <h2 class=category_title>
      New Post
    </h2>
    <ul style = "list-style:none" class = "col-md-4 col-md-offset-4">
        <li><input class="new_post" placeholder="本のタイトル" type="text" name="title" value="<%= @title %>"></li>
        <li><input class="new_post" placeholder="著者名" type="text" name="author" value="<%= @author %>"></li>
        <li><input class="new_post" placeholder="出版社" type="text" name="publisher" value = "<%= @publisher %>"></li>
        <li><input class="new_post" placeholder="Image Url" type="text" name="image" value = "<%= @book_image %>"></li>
        <li class="evaluation">
              <input id="star1" type="radio" name="rate" value="5" />
              <label for="star1"><span class="text"></span>★</label>
              <input id="star2" type="radio" name="rate" value="4" />
              <label for="star2"><span class="text"></span>★</label>
              <input id="star3" type="radio" name="rate" value="3" />
              <label for="star3"><span class="text"></span>★</label>
              <input id="star4" type="radio" name="rate" value="2" />
              <label for="star4"><span class="text"></span>★</label>
              <input id="star5" type="radio" name="rate" value="1" />
              <label for="star5"><span class="text"></span>★</label>
        </li>
        <li><textarea class = "review" cols="55" name="review" placeholder="誰に勧めたいか・要約(あらすじ)・感想・分析など" rows="30"></textarea></li>
        <li><Button class = "button_type submit_button" type="submit">SEND</Button></li>
    </ul>
  <% end %>
  </div>
</div>

app/views/books/search.html.erb
<div>
  <h2 class=category_title>Search</h2>
    <div class="search">
        <%= form_tag('/books/search', method: :get) do %>
        <input class = "input" style="width:300px;height:35px;" placeholder="本のタイトルを打ち込んでください" name = "keyword" ><button class="search_button button_type" title="search" type="submit"><span class="glyphicon glyphicon-search"></span>Search</button>
        <% end %>
        <a href="/books/new">本が見つからな人はこちら</a>
    </div>
</div>

<h2 class=category_title>Search Results</h2>
<% if @items.present? %>
  <div class="row row-eq-height">
    <% @items.each do |item| %>

      <div class="col-md-4 col-sm-5 col-sm-offset-1 col-xs-10 col-xs-offset-1 book_container">
        <div class = "row" >
             <div class="col-md-4 book_image">
                <%= image_tag item["Item"]["largeImageUrl"] %>
             </div>
             <div class="col-md-6 text">
                     <h4> <%=link_to item["Item"]["title"], new_book_path(
                        title: item["Item"]["title"],
                        author: item["Item"]["author"],
                        book_image: item["Item"]["mediumImageUrl"],
                        publisher:  item["Item"]["publisherName"] )%></h4>
                     <p> 著者名: <%= item["Item"]["author"] %> <p>
                     <p> 出版社: <%= item["Item"]["publisherName"] %> <p>
                     <p> 紹介文: <%= item["Item"]["itemCaption"] %> <p>
             </div>



            <%= link_to "", new_book_path(
                        title: item["Item"]["title"],
                        author: item["Item"]["author"],
                        book_image: item["Item"]["mediumImageUrl"],
                        publisher:  item["Item"]["publisherName"] ),
                        class: "col-md-1 glyphicon glyphicon-chevron-right"%>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/show.html.erb
<h2 class= category_title> Book Details </h2>
<div class="col-md-4 col-md-offset-4 book_container">
  <div class = "row" >
      <div class="col-md-4 book_image"><img src=<%= @book.image %>>
      </div>
      <div class="col-md-7 text">
            <h4><%= @book.title %></h4>
            <p>著者名：<%= @book.author %><p>
            <p>出版社：<%= @book.publisher %><p>
            <i class="glyphicon glyphicon-user"></i><a href="/users/<%= @book.user_id %>"><%= @book.user.name %></a>
          <div class="wrap">
            <span class="rate rate<%= @book.rate %>"></span>
          </div>
            <p class=review_detail_contents><%= @book.review %></p>
            <div class="book_amazon"><%= link_to"購入を検討>>","http://amazon.jp/gp/search?ie=UTF8&keywords=#{@book.title}#{@book.author}", target: "_blank" %>
            </div>
      </div>
  </div>
</div>
<div class="row">
   <div class = "col-md-4 col-md-offset-4 comment_form">
    <% if current_user %>
      <%= form_tag("/books/#{@book.id}/comments", method: :post) do %>
        <textarea class="textarea" cols="75" name="text" placeholder="コメントする" rows="5"></textarea>
        <button class = "submit_button button_type" type="submit"> SEND </button>
       <% end %>
    <% end %>
   </div>


  <div class = "col-md-4 col-md-offset-4 comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.name, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>

</div>

app/views/books/update.html.erb
<div class="col-md-4 col-md-offset-4">
    <div>
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BooKnit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Pinyon+Script" rel="stylesheet">
  <link href="https://fonts.googleapis.com/earlyaccess/sawarabimincho.css" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/earlyaccess/hannari.css" rel="stylesheet" />
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>
  <header>
       <div class="heading">
           <h1>BooKnit</h1>
             <div>
                <h2 class="subtitle">People don’t realize <br>
                       how a man’s whole life can be changed by one book.<br><br>
               </h2>
               <h2 class="subtitle_a">
                 「一冊の本に人生を丸ごと変えてしまう力があることを、<br>
                 みんな理解していない」
               </h2>
             </div>
      </div>

   <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
        </div>
      <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
         <li class = "nav_button"><a href="/" class="nav_button" date-toggle="tab">Home</a></li>
         <li class = "nav_button"><a href="#">About</a></li>
         <li class = "nav_button"><%= link_to "Search & New Post", books_search_path, class: 'post'%></li>
      </ul>
    <% if current_user %>
      <ul class="nav navbar-nav navbar-right">
         <li class = "nav_button" ><%= link_to "My Page", "/users/#{current_user.id}" %></li>
         <li class = "nav_button" ><%= link_to "Sign out", destroy_user_session_path, id: "sign_out" ,method: :delete%></li></ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
         <li class = "nav_button" id ="log_in"><%= link_to "Log In", user_session_path, class: 'post' %></li>
         <li class = "nav_button" id ="sign_up"><%= link_to "Sign Up", new_user_registration_path %></li>
      </ul>
    <% end %>
       </div>
      </div>
   </nav>
</header>
<% if user_signed_in? %>
<h4 class="yokoso"> ようこそ<%= current_user.name %>さま <h4>
<% end %>

<%= yield %>

<footer>
   <div class="container">

  <div class="footA">
    <h2>BooKnit</h2>
    <p>
    〒238-0032 神奈川県横須賀市平作山大光寺<br>
    <a href="http://logger.nett/">http://booknit.com/</a>
    </p>

    <nav class="footD">
      <ul>
        <li><a href="#">
          <span class="fa fa-twitter"
           title="Twitter"></span>
        </a></li>

        <li><a href="#">
          <span class="fa fa-facebook"
           title="Facebook"></span>
        </a></li>

        <li><a href="#">
          <span class="fa fa-google-plus"
           title="Google Plus"></span>
        </a></li>

        <li><a href="#">
          <span class="fa fa-instagram"
           title="Instagram"></span>
        </a></li>

        <li><a href="#">
          <span class="fa fa-youtube"
           title="YouTube"></span>
        </a></li>
      </ul>
    </nav>
  </div>

  <nav class="footB">
    <div>
      <h3>ABOUT</h3>
      <ul>
        <li><a href="#">設立</a></li>
        <li><a href="#">所在地</a></li>
        <li><a href="#">地図</a></li>
        <li><a href="#">スタッフ</a></li>
      </ul>
    </div>

    <div>
      <h3>SUPPORT</h3>
      <ul>
        <li><a href="#">ダウンロード</a></li>
        <li><a href="#">マニュアル</a></li>
        <li><a href="#">よくある質問</a></li>
        <li><a href="#">お問い合わせ</a></li>
      </ul>
    </div>

    <div>
      <h3>CONTENTS</h3>
      <ul>
        <li><a href="#">お知らせ</a></li>
        <li><a href="#">ビジネス</a></li>
        <li><a href="#">プロフィール</a></li>
        <li><a href="#">開発者</a></li>
        <li><a href="#">ブログ</a></li>
      </ul>
    </div>
  </nav>

  <div class="footC">
    © BooKnit corp. All rights reserved.
  </div>

</div>
</footer>

</body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if book.like_user(current_user.id) %>
    <%= link_to book_like_path(book_id: book.id, id: like.id), method: :delete, remote: true do %>
       <%= image_tag("check_book.svg", :class => "like_image") %>
     <% end %>
     <p class=likes_count>(<%= book.likes_count %>)<p>
  <% else %>
    <%= link_to book_likes_path(book.id), method: :post, remote: true do %>
    <%= image_tag("book.svg", :class => "like_image") %>
    <% end %>
        <p class=likes_count>(<%= book.likes_count %>)<p>
  <% end %>
<% else %>
   <%= image_tag("book.svg", :class => "like_image") %>
   <p class=likes_count>(<%= book.likes_count %>)<p>
<% end %>

app/views/likes/create.js.erb
$("#like-button<%= @book.id %>").html("<%= j(render partial: 'likes/like', locals: { book: @book, like: @book.likes.where(user_id: current_user.id).first}) %>");
console.log("a")

app/views/likes/destroy.js.erb
$("#like-button<%= @book.id %>").html("<%= j(render partial: 'likes/like', locals: { book: @book, like: @book.likes.where(user_id: current_user.id).first}) %>");
console.log("a")

app/views/users/show.html.erb
<div class = "contents">
<h2 class= category_title_mypage> <%= @name %>さんのPage</h2>

<div class="row row-eq-height">
  <div class="col-md-6">
    <h3 class="user_book_bookshelf"> Bookshelf </h3>
      <% @books.each do |book| %>
       <div class  ="row row-eq-height" >
        <div class="col-md-7 col-md-offset-3 col-sm-7 col-sm-offset-3 col-xs-7 col-xs-offset-3 book_container">
         <div class = "row" >
            <div class="col-md-4 book_image"><img src=<%= book.image %>>
            </div>
            <div class="col-md-6 text">
                <a href="/books/<%=book.id%>}">
                      <h4><%= book.title %></h4>
                </a>
                <p>著者名：<%= book.author %><p>
                <p>出版社：<%= book.publisher %><p>
                <div class="wrap">
                    <span class="rate rate<%=book.rate%>"></span>
                </div>
                  <p class=review_contents><%= book.review %></p>
                  <a class = comment href="/books/<%=book.id%>"> More >> </a>
            </div>
            <div class="dropdown  col-md-1">
           <% if user_signed_in? && current_user.id == book.user_id %>
                 <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">MENU<span class="caret"></span></button>
                    <ul class="dropdown-menu">
                      <li class="dropdown-item"><%= link_to '編集', "/books/#{book.id}/edit", method: :get %></li>
                      <li class="dropdown-item"><%= link_to '削除', "/books/#{book.id}", method: :delete %></li>
                    </ul>
            <% end %>
             </div>
            </div>
         </div>
        </div>
      <% end %>
  </div>

  <div class = "col-md-6 ">
    <h3 class= "user_book_bookmarks" > Bookmarks </h3>
    <% @bookmarks.each do |book| %>
       <div class  ="row row-eq-height" >
        <div class="col-md-7 col-md-offset-2 col-sm-7 col-sm-offset-2 col-xs-7 col-xs-offset-2 book_container">
           <div class = "row" >
             <div class="col-md-4 book_image"><img src=<%= book.image %>>
             </div>
             <div class="col-md-6 text">
                <a href="/books/<%=book.id%>}">
                  <h4><%= book.title %></h4>
                 </a>
                   <p>著者名：<%= book.author %><p>
                   <p>出版社：<%= book.publisher %><p>
                   <i class="glyphicon glyphicon-user"></i><a href="/users/<%= book.user_id %>"><%= book.user.name %></a>
                <div class="wrap">
                  <span class="rate rate<%=book.rate%>"></span>
                </div>
               <p class=review_contents><%= book.review %></p>
               <a class = comment href="/books/<%=book.id%>"> More >> </a>
               <div class="book_amazon"><%= link_to"購入を検討>>","http://amazon.jp/gp/search?ie=UTF8&keywords=#{book.title}#{book.author}", target: "_blank" %>
              </div>
             </div>
             <div id= "like-button<%= book.id %>", class="col-md-1 likes">
                <%= render partial: "likes/like", locals: { book: book, like: book.likes.where(user_id: current_user.id).first } %>
            </div>
          </div>
        </div>
      </div>
   <% end %>
  </div>
</div>
</div>